### PR TITLE
account for Deletions followed by Insertions

### PR DESCRIPTION
**Pull request by ionox0**
@rhshah @andurill @zengzheng123

### CODE REVIEW

**Comment by ionox0** [comment]
Similarly to the additional_insertion check on line 1933, variants will not be genotyped if they consist of a Deletion followed by an Insertion (e.g. 10M10D10I)

I just copied the check to the cigar D / N case as well. 

[test_data.tar.gz](https://github.com/msk-access/GetBaseCountsMultiSample/files/7206474/test_data.tar.gz) 

Here is a test bam file with 4 reads

They have a DEL-INS which is also in test.maf

GAACTGAATTC --> TGGAGTCA

11 Base deletion --> 8 base insertion

**Comment by rhshah** [comment]
@zengzheng123 or @andurill  would you be able to review this pull request

**Comment by zengzheng123** [comment]
Looks good to me.

**Comment by rhshah** [comment]
Do you envision any other scenarios that we are missing!

**Comment by zengzheng123** [comment]
> Do you envision any other scenarios that we are missing!

No, I can't think of anything that is missing.

**Pull request merged**
